#!/usr/bin/env python3
"""
Generate a docker-compose.yml from a DER Twin site config.

Usage:
    python generate_compose.py configs/simple_config.json
    python generate_compose.py configs/my_site.json --output docker-compose.yml

The generated file maps exactly the ports declared in the site config,
so no manual port management is needed.
"""

import argparse
import json
import sys
from pathlib import Path


def extract_ports(config: dict) -> list[int]:
    ports = []
    for asset in config.get("assets", []):
        for protocol in asset.get("protocols", []):
            port = protocol.get("port")
            if port and port not in ports:
                ports.append(port)
    return sorted(ports)


def generate_compose(config: dict, config_path: Path) -> str:
    ports = extract_ports(config)
    site_name = config.get("site_name", "dertwin-site")

    if not ports:
        print("Warning: no Modbus ports found in config — no ports will be exposed.", file=sys.stderr)

    port_lines = "\n".join(f'      - "{p}:{p}"' for p in ports)

    # Config path relative to repo root for the volume mount
    config_rel = config_path.resolve().relative_to(Path.cwd())
    config_dir = config_rel.parent

    compose = f"""\
# Auto-generated by generate_compose.py from {config_rel}
# Regenerate after changing port assignments in your site config.

services:

  simulator:
    build: .
    container_name: {site_name}
    environment:
      - CONFIG_PATH=/app/{config_rel}
    volumes:
      - ./{config_dir}:/app/{config_dir}:ro
    ports:
{port_lines}
    restart: unless-stopped
"""
    return compose


def main():
    parser = argparse.ArgumentParser(description="Generate docker-compose.yml from a DER Twin site config.")
    parser.add_argument("config", help="Path to site config JSON file")
    parser.add_argument("--output", default="docker-compose.yml", help="Output file (default: docker-compose.yml)")
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"Error: config file not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    with open(config_path) as f:
        config = json.load(f)

    compose = generate_compose(config, config_path)
    output_path = Path(args.output)
    output_path.write_text(compose)

    ports = extract_ports(config)
    print(f"Generated {output_path} for site '{config.get('site_name')}'")
    print(f"Exposed ports: {', '.join(str(p) for p in ports)}")
    print(f"\nTo run:")
    print(f"  docker compose up --build")


if __name__ == "__main__":
    main()