#!/usr/bin/env python3
"""
Generate a docker-compose.yml from a DER Twin site config.

Usage:
    python generate_compose.py configs/simple_config.json
    python generate_compose.py configs/mixed_protocol_config.json
    python generate_compose.py configs/my_site.json --output docker-compose.yml

For TCP-only configs, generates a standard compose file.

For configs with RTU serial ports, the entrypoint bridges each RTU
device to a TCP port (starting at 56001). The compose file exposes
these bridge ports so the host can connect via socat.
"""

import argparse
import json
import sys
from pathlib import Path

RTU_BRIDGE_BASE_PORT = 56001


def extract_tcp_ports(config: dict) -> list[int]:
    ports = []
    for asset in config.get("assets", []):
        for protocol in asset.get("protocols", []):
            if protocol.get("kind") != "modbus_tcp":
                continue
            port = protocol.get("port")
            if isinstance(port, int) and port not in ports:
                ports.append(port)
    return sorted(ports)


def extract_rtu_info(config: dict) -> list[dict]:
    """Extract RTU serial port paths with their bridge port assignments."""
    rtu_devices = []
    bridge_port = RTU_BRIDGE_BASE_PORT
    for asset in config.get("assets", []):
        for protocol in asset.get("protocols", []):
            if protocol.get("kind") != "modbus_rtu":
                continue
            serial_port = protocol.get("port", "")
            basename = serial_port.split("/")[-1]
            rtu_devices.append({
                "serial_port": serial_port,
                "basename": basename,
                "bridge_port": bridge_port,
            })
            bridge_port += 1
    return rtu_devices


def generate_compose(config: dict, config_path: Path) -> str:
    tcp_ports = extract_tcp_ports(config)
    rtu_devices = extract_rtu_info(config)
    site_name = config.get("site_name", "dertwin-site")

    if not tcp_ports and not rtu_devices:
        print("Warning: no Modbus ports found in config.", file=sys.stderr)

    config_rel = config_path.resolve().relative_to(Path.cwd())
    config_dir = config_rel.parent

    # Collect all ports to expose (TCP + RTU bridge)
    all_ports = list(tcp_ports) + [d["bridge_port"] for d in rtu_devices]

    ports_section = ""
    if all_ports:
        port_lines = "\n".join(f'      - "{p}:{p}"' for p in sorted(all_ports))
        ports_section = f"""    ports:
{port_lines}
"""

    # Build RTU comment with host-side socat commands
    rtu_comment = ""
    if rtu_devices:
        socat_cmds = []
        for d in rtu_devices:
            socat_cmds.append(
                f"    #   socat pty,raw,echo=0,link=/tmp/{d['basename']}_client "
                f"tcp:localhost:{d['bridge_port']} &"
            )
        socat_block = "\n".join(socat_cmds)

        rtu_comment = f"""
    # RTU devices are bridged to TCP ports by the entrypoint.
    # To connect from the host, create local PTY endpoints with socat:
    #
{socat_block}
    #
    # Then point your EMS at the /tmp/*_client paths as usual.
"""

    env_lines = [f"      - CONFIG_PATH=/app/{config_rel}"]
    if rtu_devices:
        env_lines.append(f"      - RTU_BRIDGE_BASE_PORT={RTU_BRIDGE_BASE_PORT}")
    env_section = "\n".join(env_lines)

    compose = f"""\
# Auto-generated by generate_compose.py from {config_rel}
# Regenerate after changing port assignments in your site config.

services:

  simulator:
    build: .
    container_name: {site_name}
    environment:
{env_section}
    volumes:
      - ./{config_dir}:/app/{config_dir}:ro
{ports_section}{rtu_comment}    restart: unless-stopped
"""
    return compose


def main():
    parser = argparse.ArgumentParser(
        description="Generate docker-compose.yml from a DER Twin site config."
    )
    parser.add_argument("config", help="Path to site config JSON file")
    parser.add_argument(
        "--output", default="docker-compose.yml",
        help="Output file (default: docker-compose.yml)",
    )
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"Error: config file not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    with open(config_path) as f:
        config = json.load(f)

    compose = generate_compose(config, config_path)
    output_path = Path(args.output)
    output_path.write_text(compose)

    tcp_ports = extract_tcp_ports(config)
    rtu_devices = extract_rtu_info(config)

    print(f"Generated {output_path} for site '{config.get('site_name')}'")

    if tcp_ports:
        print(f"Modbus TCP ports: {', '.join(str(p) for p in tcp_ports)}")

    if rtu_devices:
        print(f"RTU bridge ports: {', '.join(str(d['bridge_port']) for d in rtu_devices)}")
        print()
        print("To connect RTU devices from the host, run:")
        for d in rtu_devices:
            print(
                f"  socat pty,raw,echo=0,link=/tmp/{d['basename']}_client "
                f"tcp:localhost:{d['bridge_port']} &"
            )

    print(f"\nTo run:")
    print(f"  docker compose up --build")


if __name__ == "__main__":
    main()