telemetry:
  - address: 0
    name: inverter_status
    func: 0x04
    type: uint16
    count: 1
    scale: 1
    unit: ''
  - address: 1
    name: total_input_power
    func: 0x04
    type: uint32
    count: 2
    scale: 0.1
    unit: W
  - address: 35
    name: total_active_power
    func: 0x04
    type: uint32
    count: 2
    scale: 0.1
    unit: W
  - address: 37
    name: grid_frequency
    func: 0x04
    type: uint16
    count: 1
    scale: 0.01
    unit: Hz
  - address: 53
    name: today_output_energy
    func: 0x04
    type: uint32
    count: 2
    scale: 0.1
    unit: kWh
  - address: 55
    name: lifetime_output_energy
    func: 0x04
    type: uint32
    count: 2
    scale: 0.1
    unit: kWh
  - address: 93
    name: temp_inverter
    func: 0x04
    type: int16
    count: 1
    scale: 0.1
    unit: degC
  - address: 100
    name: power_factor
    func: 0x04
    type: uint16
    count: 1
    scale: 1
    unit: ''
  - address: 105
    name: fault_code
    func: 0x04
    type: uint16
    count: 1
    scale: 1
    unit: ''
