commands:
  - address: 0
    name: remote_on_off
    func: 0x06
    type: uint16
    options:
      0: Off
      1: On
  - address: 3
    name: active_power_rate
    func: 0x06
    type: uint16
    scale: 1
    unit: "%"
  - address: 4
    name: reactive_power_rate
    func: 0x06
    type: uint16
    scale: 1
    unit: "%"
  - address: 5
    name: power_factor
    func: 0x06
    type: uint16
