commands:
  - address: 4099
    name: current_transformer_ratio
    func: 0x06
    type: uint32
    scale: 0.1
  - address: 4101
    name: voltage_transformer_ratio
    func: 0x06
    type: uint32
    scale: 0.1
  - address: 4112
    name: interval_time
    func: 0x06
    type: uint32
